name: Android CI

on:
  push:
    branches: [ "release-v2" ]
  pull_request:
    branches: [ "release-v2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Decrypt the artefact signing key
      run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.KEY_PROPERTIES_DECRYPT }}" --output app/key.properties secrets/key.properties.gpg

    - name: Decrypt the key store
      run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.HMS_ANDROID_JKS }}" --output ./100ms-android/app/100ms-android.jks secrets/100ms-android.jks.gpg

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bundleRelease
