name: Android CI

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  deploy-to-maven-central:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Which version
      run: echo "${{github.ref_name}}"

    - name: Decrypt the artefact signing key
      run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ANDROID_ROOM_KIT_SONATYPE_PRIVATE_KEY_DECRYPT_PASSWORD }}" --output secrets/private.pgp secrets/private.pgp.gpg

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Deploy to Maven Central live.100ms (Sonatype)
      run: ./gradlew clean publishToSonatype closeAndReleaseSonatypeStagingRepository -PhmsRoomKitGroup="live.100ms" -PHMS_ROOM_KIT_VERSION="${{github.ref_name}}" -PossrhUsername="${{ secrets.ANDROID_SONATYPE_USERNAME}}" -PossrhPassword="${{ secrets.ANDROID_SONATYPE_PASSWORD}}" -Psigning.keyId="62C0C2F9" -Psigning.password="${{ secrets.ANDROID_ROOM_KIT_SIGNING_PASSWORD }}" -Psigning.secretKeyRingFile="../secrets/private.pgp" -PTOKEN_ENDPOINT="\"​\""

